apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-db-deployment
spec:
  selector:
    matchLabels:
      app: web-db
  template:
    metadata:
      labels:
        app: web-db
    spec:
      containers:
      - name: web-db
        image: mjhuliana/practice:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 3306
      - name: web 
        image: mjhuliana/practicatecno:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 81
---
apiVersion: v1
kind: Service
metadata:
  name: dbcontainer
spec:
  type: ClusterIP
  selector:
    app: web-db
  ports:
  - name: "mysql"
    port: 3306
    targetPort: 3306
  - name: "flask"
    port: 9000
    targetPort: 81